---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/8/10 20:46
---

gtmInterface = CS.gtmInterface;

gtmGame = CS.gtmGame;

UnityEngine = CS.UnityEngine;


global = {};

---@class gtmInterface.LogCategory
global.LogCategory = gtmInterface.LogCategory;

---@class gtmInterface.ILogSystem
global.ILogSystem = gtmInterface.ILogSystem.instance;

---@class gtmGame.UIManager
global.UIManager = gtmGame.UIManager.instance;

---@class gtmGame.LuaManager
global.LuaManager = gtmGame.LuaManager.instance;

---@class gtmInterface.INetManager
global.INetManager = gtmInterface.INetManager.instance;

---@class gtmInterface.IMsgDispatcher
global.IMsgDispatcher = gtmInterface.IMsgDispatcher.instance

---@class gtmInterface.ByteBuffer
global.ByteBuffer = gtmInterface.ByteBuffer

---@class gtmInterface.Converter
global.Converter = gtmInterface.Converter

---@class gamestatetype
global.gamestatetype = require "msg.fbs.gamestatetype"

return global;

