---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/1 6:21
---

---@class ui_selrole
ui_selrole = {}

ui_selrole.uiname = "ui_panel_selrole"

---@type testmodel
ui_selrole.model = nil


----------------------------------------------内置-------------------------------------------------

function ui_selrole.show()

    if ui_selrole.isShow then
        return
    end

    ---@type gtmGame.Dialog
    ui_selrole.dialog = ui_mgr.createDialog(ui_selrole.uiname, "ui_selrole")

    if not ui_selrole.dialog then
        print("ui_selrole.dialog null uiname " .. ui_selrole.uiname)
    end

    ui_selrole.isShow = true

    ui_selrole.initui()
    ui_selrole.initEvent()
    ui_selrole.initData()
end

function ui_selrole.close()
    ui_mgr.closeDialog(ui_selrole.uiname)
end

function ui_selrole.preShow()
    print("ui_selrole.preShow")
end

function ui_selrole.preHide()
    print("ui_selrole.preHide")
end

function ui_selrole.preClose()
    print("ui_selrole.preClose")

    ui_selrole.isShow = false
    ui_selrole.uiref = {}

    ui_selrole.removeEvent()
    ui_selrole.clearData()
end

--- initui
function ui_selrole.initui()
    ui_selrole.uiref = {}

end

--- init event
function ui_selrole.initEvent()

end

--- remove event
function ui_selrole.removeEvent()

end

function ui_selrole.initData()

end

function ui_selrole.clearData()

end

--------------------------------------------------------------------------------------------------












-------------------------------------------ui事件-------------------------------------------------



--------------------------------------------------------------------------------------------------













---------------------------------------------外部事件----------------------------------------------



--------------------------------------------------------------------------------------------------












-----------------------------------------------函数------------------------------------------------



--------------------------------------------------------------------------------------------------






return ui_selrole