---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/1 12:19
---


local event = require("base.event")

---@class basestate
local basestate = luaclass(function (self)
    self.evententer = event:new()
    self.eventrefresh = event:new()
    self.eventexit = event:new()
end);

function basestate:onEnter(self)
    print("baseclass.onEnter")

    if self.evententer then
        self.evententer()
    end
end

function basestate:onExit(self)
    print("baseclass.onExit")

    if self.eventexit then
        self.eventexit()
    end
end

function basestate:onRefresh(self)
    print("basestate.onRefresh")

    if self.eventrefresh then
        self.eventrefresh()
    end
end

return basestate;