---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/1 12:19
---

--local baseclass = require("base.luaclass")
local event = require("base.eventlib")

---@class basestate
basestate = luaclass(function(self)
    self.eventTest = event:new()
end);

function basestate.onEnter()
    print("baseclass.onEnter")
end

function basestate.onExit()
    print("baseclass.onExit")
end

function basestate.onRefresh()
    print("basestate.onRefresh")
end

return baseclass;