---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/1 12:20
---

local basestate = require("gamestate.basestate")
local event = require("base.eventlib")

---@class gamestate
local gamestate = luaclass(basestate)

gamestate.evententer = event:new()
gamestate.eventrefresh = event:new()
gamestate.eventexit = event:new()

function gamestate.onEnter()
    print("gamestate.onEnter")

    if gamestate.evententer then
        gamestate.evententer:Fire()
    end
end

function gamestate.onExit()
    print("gamestate.onExit")

    if gamestate.eventexit then
        gamestate.eventexit:Fire()
    end
end

function gamestate.onRefresh()
    print("gamestate.onRefresh")

    if gamestate.eventrefresh then
        gamestate.eventrefresh:Fire()
    end
end

return gamestate:new()