---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/1 12:21
---

---@class gamestatemgr
gamestatemgr = {}

function gamestatemgr.register()
    
end

function gamestatemgr.changeState()

end

return gamestatemgr