---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/1 12:20
---

local basestate = require("gamestate.basestate")

---@class gamestate
local gamestate = luaclass(basestate)

function gamestate.onEnter()
    print("gamestate.onEnter")

    basestate.onEnter()
end

function gamestate.onExit()
    print("gamestate.onExit")

    basestate.onExit()
end

function gamestate.onRefresh()
    print("gamestate.onRefresh")

    basestate.onRefresh()
end

return gamestate:new()