---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/1 12:19
---

--local baseclass = require("base.luaclass")
local basestate = require("gamestate.basestate")
local event = require("base.eventlib")

---@class loginstate
loginstate = luaclass(basestate);

loginstate.evententer = event:new()
loginstate.eventrefresh= event:new()
loginstate.eventexit = event:new()

function loginstate.onEnter()
    print("loginstate.onEnter")

    loginstate.evententer:Fire()
end

function loginstate.onExit()
    print("loginstate.onExit")

    loginstate.eventexit:Fire()
end

function loginstate.onRefresh()
    print("loginstate.onRefresh")

    loginstate.eventrefresh:Fire()
end

return loginstate:new()