---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/8/31 7:52
---

local msgdispatcher = require("msgdispatcher.msgdispatcher")

local event = require("base.eventlib");

netmsgregister = {};

netmsgregister.eventConnetSuc = event:new()


-------------------------------------------事件----------------------------------------------------

function netmsgregister.onLuaMsgEvent(msgid, bytearray)

    --print("netmsgregister.onLuaMsgEvent msgid : "..msgid);

    msgdispatcher.dispatcher(msgid, bytearray)
end

function netmsgregister.onConnectSucEvent()
    print("netmsgregister.onConnectSucEvent")

    netmsgregister.eventConnetSuc:Fire()
end

--------------------------------------------------------------------------------------------------










-------------------------------------------外部调用-------------------------------------------------

function netmsgregister.init()
    global.INetManager.onLuaMsgEvent:AddListener(netmsgregister.onLuaMsgEvent)
    global.INetManager.onConnectSucEvent:AddListener(netmsgregister.onConnectSucEvent);
end

function netmsgregister.destroy()
    global.INetManager.onLuaMsgEvent:RemoveListener(netmsgregister.onLuaMsgEvent)
    global.INetManager.onConnectSucEvent:RemoveListener(netmsgregister.onConnectSucEvent);
end

--------------------------------------------------------------------------------------------------

return netmsgregister