---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/8/31 7:52
---

netmsgregister = {};


local msgdispatcher = require("msgdispatcher.msgdispatcher")


-------------------------------------------事件----------------------------------------------------

function netmsgregister.onLuaMsgEvent(msgid, bytearray)

    --print("netmsgregister.onLuaMsgEvent msgid : "..msgid);

    msgdispatcher.dispatcher(msgid, bytearray)
end

--------------------------------------------------------------------------------------------------










-------------------------------------------外部调用-------------------------------------------------

function netmsgregister.init()
    global.INetManager.onLuaMsgEvent:AddListener(netmsgregister.onLuaMsgEvent)
end

function netmsgregister.destroy()
    global.INetManager.onLuaMsgEvent:RemoveListener(netmsgregister.onLuaMsgEvent)
end

--------------------------------------------------------------------------------------------------

return netmsgregister;