-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fbs

local flatbuffers = require('flatbuffers')

---@class ReqLoginSelectZone
local ReqLoginSelectZone = {} -- the module

local ReqLoginSelectZone_mt = {} -- the class metatable

ReqLoginSelectZone.HashID = 0x15C7D80481F9C75C;

function ReqLoginSelectZone.New()
    local o = {}
    setmetatable(o, {__index = ReqLoginSelectZone_mt})
    return o
end

function ReqLoginSelectZone.GetRootAsReqLoginSelectZone(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = ReqLoginSelectZone.New()
    o:Init(buf, n + offset)
    return o
end

function ReqLoginSelectZone.init(buf, offset)
    return ReqLoginSelectZone.GetRootAsReqLoginSelectZone(buf, offset)
end

function ReqLoginSelectZone_mt:
Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end

function ReqLoginSelectZone_mt:Zoneid()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Uint16, o + self.view.pos)
    end
    return 0
end

function ReqLoginSelectZone.Start(builder) builder:StartObject(1) end
function ReqLoginSelectZone.AddZoneid(builder, zoneid) builder:PrependUint16Slot(0, zoneid, 0) end
function ReqLoginSelectZone.End(builder) return builder:EndObject() end

return ReqLoginSelectZone -- return the module