-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fbs

local flatbuffers = require('flatbuffers')

---@class ReqRegisterAccount
local ReqRegisterAccount = {} -- the module

local ReqRegisterAccount_mt = {} -- the class metatable

ReqRegisterAccount.HashID = 0x8B88EE5F49F79DC5;

function ReqRegisterAccount.New()
    local o = {}
    setmetatable(o, {__index = ReqRegisterAccount_mt})
    return o
end

function ReqRegisterAccount.GetRootAsReqRegisterAccount(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = ReqRegisterAccount.New()
    o:Init(buf, n + offset)
    return o
end

function ReqRegisterAccount.init(buf, offset)
    return ReqRegisterAccount.GetRootAsReqRegisterAccount(buf, offset)
end

function ReqRegisterAccount_mt:
Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end

function ReqRegisterAccount_mt:Account()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end

function ReqRegisterAccount_mt:Password()
    local o = self.view:Offset(6)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end

function ReqRegisterAccount.Start(builder) builder:StartObject(2) end
function ReqRegisterAccount.AddAccount(builder, account) builder:PrependUOffsetTRelativeSlot(0, account, 0) end
function ReqRegisterAccount.AddPassword(builder, password) builder:PrependUOffsetTRelativeSlot(1, password, 0) end
function ReqRegisterAccount.End(builder) return builder:EndObject() end

return ReqRegisterAccount -- return the module