-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fbs

local gamestatetype = {
    invalid = 0,
    login = 1,
    register = 2,
    game = 3,
}

return gamestatetype -- return the module