-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fbs

local gamestatetype = {
    invalid = 0,
    selectserver = 1,
    login = 2,
    register = 3,
    game = 4,
}

return gamestatetype -- return the module