-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fbs

local flatbuffers = require('3rd.flatbuffers')

---@class RepLoginGame
local RepLoginGame = {} -- the module

local RepLoginGame_mt = {} -- the class metatable

RepLoginGame.HashID = 0x53BC116151C382CF;

function RepLoginGame.New()
    local o = {}
    setmetatable(o, {__index = RepLoginGame_mt})
    return o
end

function RepLoginGame.GetRootAsRepLoginGame(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = RepLoginGame.New()
    o:Init(buf, n + offset)
    return o
end

function RepLoginGame.init(buf, offset)
    return RepLoginGame.GetRootAsRepLoginGame(buf, offset)
end

function RepLoginGame_mt:
Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end

function RepLoginGame.Start(builder) builder:StartObject(0) end
function RepLoginGame.End(builder) return builder:EndObject() end

return RepLoginGame -- return the module