-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fbs

local flatbuffers = require('3rd.flatbuffers')

---@class ReqLoginAccount
local ReqLoginAccount = {} -- the module

local ReqLoginAccount_mt = {} -- the class metatable

ReqLoginAccount.HashID = 0x30526426CFB42CCF;

function ReqLoginAccount.New()
    local o = {}
    setmetatable(o, {__index = ReqLoginAccount_mt})
    return o
end

function ReqLoginAccount.GetRootAsReqLoginAccount(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = ReqLoginAccount.New()
    o:Init(buf, n + offset)
    return o
end

function ReqLoginAccount.init(buf, offset)
    return ReqLoginAccount.GetRootAsReqLoginAccount(buf, offset)
end

function ReqLoginAccount_mt:
Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end

function ReqLoginAccount_mt:Account()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end

function ReqLoginAccount_mt:Password()
    local o = self.view:Offset(6)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end

function ReqLoginAccount.Start(builder) builder:StartObject(2) end
function ReqLoginAccount.AddAccount(builder, account) builder:PrependUOffsetTRelativeSlot(0, account, 0) end
function ReqLoginAccount.AddPassword(builder, password) builder:PrependUOffsetTRelativeSlot(1, password, 0) end
function ReqLoginAccount.End(builder) return builder:EndObject() end

return ReqLoginAccount -- return the module