-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fbs

local flatbuffers = require('3rd.flatbuffers')

---@class RspConnectSuc
local RspConnectSuc = {} -- the module

local RspConnectSuc_mt = {} -- the class metatable

RspConnectSuc.HashID = 0x28848DCC94CF95A9;

function RspConnectSuc.New()
    local o = {}
    setmetatable(o, {__index = RspConnectSuc_mt})
    return o
end

function RspConnectSuc.GetRootAsRspConnectSuc(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = RspConnectSuc.New()
    o:Init(buf, n + offset)
    return o
end

function RspConnectSuc.init(buf, offset)
    return RspConnectSuc.GetRootAsRspConnectSuc(buf, offset)
end

function RspConnectSuc_mt:
Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end

function RspConnectSuc.Start(builder) builder:StartObject(0) end
function RspConnectSuc.End(builder) return builder:EndObject() end

return RspConnectSuc -- return the module