-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fbs

local flatbuffers = require('3rd.flatbuffers')

---@class RspLoginRoleList
local RspLoginRoleList = {} -- the module

local RspLoginRoleList_mt = {} -- the class metatable

RspLoginRoleList.HashID = 0x6A710EC29C49A4CB;

function RspLoginRoleList.New()
    local o = {}
    setmetatable(o, {__index = RspLoginRoleList_mt})
    return o
end

function RspLoginRoleList.GetRootAsRspLoginRoleList(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = RspLoginRoleList.New()
    o:Init(buf, n + offset)
    return o
end

function RspLoginRoleList.init(buf, offset)
    return RspLoginRoleList.GetRootAsRspLoginRoleList(buf, offset)
end

function RspLoginRoleList_mt:
Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end

function RspLoginRoleList.Start(builder) builder:StartObject(0) end
function RspLoginRoleList.End(builder) return builder:EndObject() end

return RspLoginRoleList -- return the module