---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/8 16:10
---

local skynet = require "skynet"
local mysql = require "skynet.db.mysql"

skynet.start(function()

    local function on_connect(db)
        skynet.error("on_connect")
    end

    local db = mysql.connect({
        host = "192.168.0.108",
        port = 3306,
        database = "skynet",
        user = "root",
        password = "12345678",
        max_packet_size = 1024 * 1024,
        on_connect = on_connect
    })
end)
