---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/8/29 22:44
---

ui_test = {}

ui_test.uiname = "ui_test"

---@type gtmGame.UIManager
ui_test.uimgr = global.UIManager;

ui_test.show = function()
    ui_test.uiroot = ui_test.uimgr:CreateDialog(ui_test.uiname, "ui_test");
end

ui_test.close = function()
    ui_test.uimgr.CloseDialog(ui_test.uiname);
end


return ui_test;