---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/2 22:43
---

local function callcons(mt, tb, ...)
    if mt.constructor ~= nil then
        mt.constructor(tb, ...)
        return
    end

    local supermeta = getmetatable(mt)
    if supermeta ~= nil and supermeta.constructor ~= nil then
        callcons(supermeta, tb, ...)
    end
end

function luaclass(p1, p2)
    local superclass
    local constructor

    if type(p1) == "table" then superclass = p1 end
    if type(p1) == "function" then constructor = p1 end
    if type(p2) == "function" then constructor = p2 end

    local tb = {}
    tb.__is_class = true
    tb.constructor = constructor
    tb.__index = tb

    if superclass == nil then
        tb.new = function(self, ...)
            local t = {}
            setmetatable(t, self)
            callcons(self, t, ...)

            return t
        end

        tb.placementNew = function(self, t, ...)
            t = t or {}
            setmetatable(t, self)
            callcons(self, t, ...)

            return t
        end
    else
        setmetatable(tb, superclass)
    end

    return tb
end
