---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/8/31 10:30
---

local loginmodel = require("clientmodel.loginmodel.loginmodel")
local registermodel = require("clientmodel.registermodel.registermodel")
local selectservermodel = require("clientmodel.selectservermodel.selectservermodel")

---@class clientmodelmgr
clientmodelmgr = {}


function clientmodelmgr.register()
    loginmodel.create()
    registermodel.create()
    selectservermodel.create()
end

function clientmodelmgr.unregister()
    loginmodel.close()
    registermodel.close()
    selectservermodel.close()
end


return clientmodelmgr;













--testmodel.create()
--testmodel.close()
--local testmodel = require("clientmodel.testmodel.testmodel")