---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/8/31 10:30
---

local testmodel = require("clientmodel.testmodel.testmodel")

---@class clientmodelmgr
clientmodelmgr = {}


function clientmodelmgr.register()
    testmodel.create()
end

function clientmodelmgr.unregister()
    testmodel.close()
end


return clientmodelmgr;