---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/1 6:33
---

---@type msgdispatcher
local msgdispatcher = require("msgdispatcher.msgdispatcher")


---@class modeltemplate
modeltemplate = {}


---------------------------------------继承函数---------------------------------------

function modeltemplate.create()

end

function modeltemplate.close()

end

--------------------------------------------------------------------------------------


return modeltemplate;
