// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

public enum gamestatetype : ushort
{
 invalid = 0,
 selectserver = 1,
 login = 2,
 register = 3,
 game = 4,
};


}
