// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

public enum gamestate : ushort
{
 invalid = 0,
 login = 1,
 register = 2,
 game = 3,
};


}
