// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

public enum gamestatetype : ushort
{
 invalid = 0,
 login = 1,
 game = 2,
};


}
