// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::FlatBuffers;

public struct RepLoginGame : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public const ulong HashID = 0x53BC116151C382CF;
  public static RepLoginGame GetRootAsRepLoginGame(ByteBuffer _bb) { return GetRootAsRepLoginGame(_bb, new RepLoginGame()); }
  public static RepLoginGame GetRootAsRepLoginGame(ByteBuffer _bb, RepLoginGame obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RepLoginGame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRepLoginGame(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<RepLoginGame> EndRepLoginGame(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RepLoginGame>(o);
  }
};


}
