// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::FlatBuffers;

public struct ReqLoginSelectZone : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public const ulong HashID = 0x15C7D80481F9C75C;
  public static ReqLoginSelectZone GetRootAsReqLoginSelectZone(ByteBuffer _bb) { return GetRootAsReqLoginSelectZone(_bb, new ReqLoginSelectZone()); }
  public static ReqLoginSelectZone GetRootAsReqLoginSelectZone(ByteBuffer _bb, ReqLoginSelectZone obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReqLoginSelectZone __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort Zoneid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }

  public static Offset<ReqLoginSelectZone> CreateReqLoginSelectZone(FlatBufferBuilder builder,
      ushort zoneid = 0) {
    builder.StartObject(1);
    ReqLoginSelectZone.AddZoneid(builder, zoneid);
    return ReqLoginSelectZone.EndReqLoginSelectZone(builder);
  }

  public static void StartReqLoginSelectZone(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddZoneid(FlatBufferBuilder builder, ushort zoneid) { builder.AddUshort(0, zoneid, 0); }
  public static Offset<ReqLoginSelectZone> EndReqLoginSelectZone(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ReqLoginSelectZone>(o);
  }
};


}
