// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::FlatBuffers;

public struct RspLoginGame : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public const ulong HashID = 0xE31B3F10FDB63C51;
  public static RspLoginGame GetRootAsRspLoginGame(ByteBuffer _bb) { return GetRootAsRspLoginGame(_bb, new RspLoginGame()); }
  public static RspLoginGame GetRootAsRspLoginGame(ByteBuffer _bb, RspLoginGame obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RspLoginGame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte Ok { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<RspLoginGame> CreateRspLoginGame(FlatBufferBuilder builder,
      byte ok = 0) {
    builder.StartObject(1);
    RspLoginGame.AddOk(builder, ok);
    return RspLoginGame.EndRspLoginGame(builder);
  }

  public static void StartRspLoginGame(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddOk(FlatBufferBuilder builder, byte ok) { builder.AddByte(0, ok, 0); }
  public static Offset<RspLoginGame> EndRspLoginGame(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RspLoginGame>(o);
  }
};


}
