// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::FlatBuffers;

public struct RspLoginSelectZone : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public const ulong HashID = 0x569DFA3DC8ECEB19;
  public static RspLoginSelectZone GetRootAsRspLoginSelectZone(ByteBuffer _bb) { return GetRootAsRspLoginSelectZone(_bb, new RspLoginSelectZone()); }
  public static RspLoginSelectZone GetRootAsRspLoginSelectZone(ByteBuffer _bb, RspLoginSelectZone obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RspLoginSelectZone __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Ok { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<RspLoginSelectZone> CreateRspLoginSelectZone(FlatBufferBuilder builder,
      bool ok = false) {
    builder.StartObject(1);
    RspLoginSelectZone.AddOk(builder, ok);
    return RspLoginSelectZone.EndRspLoginSelectZone(builder);
  }

  public static void StartRspLoginSelectZone(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddOk(FlatBufferBuilder builder, bool ok) { builder.AddBool(0, ok, false); }
  public static Offset<RspLoginSelectZone> EndRspLoginSelectZone(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RspLoginSelectZone>(o);
  }
};


}
