// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::FlatBuffers;

public struct RspLoginRoleList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public const ulong HashID = 0x6A710EC29C49A4CB;
  public static RspLoginRoleList GetRootAsRspLoginRoleList(ByteBuffer _bb) { return GetRootAsRspLoginRoleList(_bb, new RspLoginRoleList()); }
  public static RspLoginRoleList GetRootAsRspLoginRoleList(ByteBuffer _bb, RspLoginRoleList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RspLoginRoleList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRspLoginRoleList(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<RspLoginRoleList> EndRspLoginRoleList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RspLoginRoleList>(o);
  }
};


}
