// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::FlatBuffers;

public struct RspRegisterAccount : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public const ulong HashID = 0x33536FC3789AF76C;
  public static RspRegisterAccount GetRootAsRspRegisterAccount(ByteBuffer _bb) { return GetRootAsRspRegisterAccount(_bb, new RspRegisterAccount()); }
  public static RspRegisterAccount GetRootAsRspRegisterAccount(ByteBuffer _bb, RspRegisterAccount obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RspRegisterAccount __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Ok { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<RspRegisterAccount> CreateRspRegisterAccount(FlatBufferBuilder builder,
      bool ok = false) {
    builder.StartObject(1);
    RspRegisterAccount.AddOk(builder, ok);
    return RspRegisterAccount.EndRspRegisterAccount(builder);
  }

  public static void StartRspRegisterAccount(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddOk(FlatBufferBuilder builder, bool ok) { builder.AddBool(0, ok, false); }
  public static Offset<RspRegisterAccount> EndRspRegisterAccount(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RspRegisterAccount>(o);
  }
};


}
