-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fbs

local flatbuffers = require('flatbuffers')

local RspLogin = {} -- the module
local RspLogin_mt = {} -- the class metatable

function RspLogin.New()
    local o = {}
    setmetatable(o, {__index = RspLogin_mt})
    return o
end
function RspLogin.GetRootAsRspLogin(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = RspLogin.New()
    o:Init(buf, n + offset)
    return o
end
function RspLogin_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function RspLogin_mt:Isok()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return (self.view:Get(flatbuffers.N.Bool, o + self.view.pos) ~= 0)
    end
    return false
end
function RspLogin.Start(builder) builder:StartObject(1) end
function RspLogin.AddIsok(builder, isok) builder:PrependBoolSlot(0, isok, 0) end
function RspLogin.End(builder) return builder:EndObject() end

return RspLogin -- return the module