---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/1 6:33
---

---@type msgdispatcher
local msgdispatcher = require("msgdispatcher.msgdispatcher")


---@class loginmodel
loginmodel = {}


---------------------------------------继承函数---------------------------------------

function loginmodel.create()

end

function loginmodel.close()

end

--------------------------------------------------------------------------------------


return loginmodel;
