---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/1 6:33
---

---@type msgdispatcher
local msgdispatcher = require("msgdispatcher.msgdispatcher")


---@class registermodel
registermodel = {}


---------------------------------------继承函数---------------------------------------

function registermodel.create()

end

function registermodel.close()

end

--------------------------------------------------------------------------------------


return registermodel;
