---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/8/31 6:38
---

---@class ui_mgr
ui_mgr = {}

---@type gtmGame.UIManager
ui_mgr.uimgr = global.UIManager;

--- create
function ui_mgr.createDialog(uiname, luatable)
    return ui_mgr.uimgr:CreateDialog(uiname, luatable);
end

--- close
function ui_mgr.closeDialog(uiname)
    return ui_mgr.uimgr:CloseDialog(uiname);
end

return ui_mgr;