---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/1 6:21
---

---@class ui_template
ui_template = {}

ui_template.uiname = "ui_template"

---@type testmodel
ui_template.model = nil


----------------------------------------------内置-------------------------------------------------

function ui_template.show()

    if ui_template.isShow then
        return
    end

    ---@type gtmGame.Dialog
    ui_template.dialog = ui_mgr.createDialog(ui_template.uiname, "ui_template")

    if not ui_template.dialog then
        print("ui_template.dialog null uiname " .. ui_template.uiname)
    end

    ui_template.isShow = true

    ui_template.initui()
    ui_template.initEvent()
    ui_template.initData()
end

function ui_template.close()
    ui_mgr.closeDialog(ui_template.uiname)
end

function ui_template.preShow()
    print("ui_template.preShow")
end

function ui_template.preHide()
    print("ui_template.preHide")
end

function ui_template.preClose()
    print("ui_template.preClose")

    ui_template.isShow = false
    ui_template.uiref = {}

    ui_template.removeEvent()
    ui_template.clearData()
end

--- initui
function ui_template.initui()
    ui_template.uiref = {}

end

--- init event
function ui_template.initEvent()

end

--- remove event
function ui_template.removeEvent()

end

function ui_template.initData()

end

function ui_template.clearData()

end

--------------------------------------------------------------------------------------------------












-------------------------------------------ui事件-------------------------------------------------



--------------------------------------------------------------------------------------------------













---------------------------------------------外部事件----------------------------------------------



--------------------------------------------------------------------------------------------------












-----------------------------------------------函数------------------------------------------------



--------------------------------------------------------------------------------------------------






return ui_template