---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/8/31 10:30
---

---@type msgdispatcher
local msgdispatcher = require("msgdispatcher.msgdispatcher")

---@type RspLogin
local rsplogin = require("msg.fbs.RspLogin")

---@type RspChat
local rspchat = require("msg.fbs.RspChat")

---@type ReqLogin
local reqlogin = require("msg.fbs.ReqLogin")

---@type ReqChat
local reqchat = require("msg.fbs.ReqChat")

---@class testmodel
testmodel = {}


function testmodel.create()

    msgdispatcher.registerFbMsg(rsplogin, testmodel.onRspLogin_sc)
    msgdispatcher.registerFbMsg(rspchat, testmodel.onRspChat_sc)
end

function testmodel.close()

    msgdispatcher.unRegisterFbMsg(rsplogin, testmodel.onRspLogin_sc)
    msgdispatcher.unRegisterFbMsg(rspchat, testmodel.onRspChat_sc)
end

function testmodel.onRspLogin_sc(msg)
    print(msg:Account())
    print(msg:Password())
end

function testmodel.onRspChat_sc(msg)
    print(msg:Say())
end

function testmodel.sendreqlogin_cs(_account, _password)

    ---@type builder
    local builder = msgdispatcher.newBuilder(1024);

    local account = builder:CreateString(_account);
    local password = builder:CreateString(_password);

    reqlogin.Start(builder)
    reqlogin.AddAccount(builder, account)
    reqlogin.AddPassword(builder, password)

    local orc = reqlogin.End(builder)
    builder:Finish(orc)

    msgdispatcher.sendFbMsg(reqlogin, builder)
end

function testmodel.sendreqchat_cs(_say)

    ---@type builder
    local builder = msgdispatcher.newBuilder(1024);

    local say = builder:CreateString(_say);

    reqchat.Start(builder)
    reqchat.AddSay(builder, say)

    local orc = reqchat.End(builder)
    builder:Finish(orc)

    msgdispatcher.sendFbMsg(reqchat, builder)
end


return testmodel;

























