---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/1 6:21
---

---@class ui_register
ui_register = {}

ui_register.uiname = "ui_register"

---@type testmodel
ui_register.model = nil


----------------------------------------------内置-------------------------------------------------

function ui_register.show()

    ---@type gtmGame.Dialog
    ui_register.dialog = ui_mgr.createDialog(ui_register.uiname, "ui_register");

    if not ui_register.dialog then
        print("ui_register.dialog null uiname " .. ui_register.uiname);
    end

    ui_register.initui();
    ui_register.initEvent();
end

function ui_register.close()
    ui_mgr.closeDialog(ui_register.uiname);
end

--- initui
function ui_register.initui()
    ui_register.uiref = {};


end

--- init event
function ui_register.initEvent()

end

--------------------------------------------------------------------------------------------------












-------------------------------------------ui事件-------------------------------------------------



--------------------------------------------------------------------------------------------------
















return ui_register;