---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xieliujian.
--- DateTime: 2019/9/1 6:33
---

---@type msgdispatcher
local msgdispatcher = require("msgdispatcher.msgdispatcher")


---@class selectservermodel
selectservermodel = {}


---------------------------------------继承函数---------------------------------------

function selectservermodel.create()

end

function selectservermodel.close()

end

--------------------------------------------------------------------------------------


return selectservermodel;
